### ISSUE TITLE
Marshmallow Schema

### ISSUE THREAD

**Issue by GendoIkari** [nbschool/ecommerce_api#10]
https://marshmallow.readthedocs.io/en/latest/quickstart.html#declaring-schemas

Con marshmallow è possibile serializzare oggetti Python complessi in json, descrivendo cosa deve essere serializzato attraverso le classi Schema.
Dobbiamo realizzare uno Schema per le varie classi del nostro model che rappresentano le risorse REST.

**Comment by toysroom** [comment]
Fatta quella per il model User
