### ISSUE TITLE
Miglioramenti modello Order

### ISSUE THREAD

**Issue by gvaldambrini** [nbschool/ecommerce_api#113]
Con una add_items eviteremo di fare scritture multiple su database ogni volta che ad un ordine viene aggiunto un item ad un ordine. Inoltre, suggerisco di esplorare le [deferred relations](http://docs.peewee-orm.com/en/latest/peewee/api.html#DeferredRelation) per vedere se si può eliminare la prima create (da cui comunque abbiamo necessità di estrarre l'oggetto creato per passarlo alla foreign key dell'OrderItem).

**Comment by marcotinacci** [comment]
Purtroppo le deferred relations di peewee riguardano solo la costruzione statica dei modelli e non delle istanze. Ho comunque risolto creando l'Order col prezzo totale già calcolato prima dei vari OrderItem.
