### ISSUE TITLE
Bug Demo-Content

### ISSUE THREAD

**Issue by simo86** [nbschool/ecommerce_api#139]
Nel file `demo_content.py` vi è un bug che con il database vuoto l'operazione write_db inserisce i dati esattamente, però se si richiama di nuovo write_db con database "pieno" da l'errore `peewee.IntegrityError: UNIQUE constraint failed` a causa del SEED univoco

**Comment by gvaldambrini** [comment]
Mettiamo che il SEED ha un valore di default hardcodato nel codice, ma che è possibile specificare un altro valore come argomento command line.
