### ISSUE TITLE
Aggiungere script demo-content

### ISSUE THREAD

**Issue by gvaldambrini** [nbschool/ecommerce_api#34]
Deve essere aggiunto uno script, nella directory `scripts`, chiamato `demo-content.py`. Lo script dovrà andare ad eliminare tutti i dati presenti nelle tabelle ed andare a generare dei dati finti (ma realistici), per tutte le tabelle presenti (in questo momento, user, item, order, orderitem)

**Comment by gvaldambrini** [comment]
Come detto a voce, eliminiamo la possibilità di creare database con nomi differenti (perché tanto l'applicazione legge sempre e solo `database.db`). Il menu principale dovrà quindi essere eliminato, e al suo posto il demo_content dovrà:
 - se il file `database.db` non è presente, creare un nuovo file, creare le tabelle e popolarle
 - se il file `database.db` esiste mostrare un menu per chiedere che cosa si vuole fare, con le opzioni: 
   * esci e non fare niente
   * sovrascrivi il vecchio database facendo il drop delle tabelle e popolandole nuovamente
   * aggiungi il contenuto demo alle tabelle già esistenti

**Comment by Chococoin** [comment]
https://github.com/nbschool/ecommerce_api/pull/105
