### ISSUE TITLE
Test utils refactoring

### ISSUE THREAD

**Issue by GendoIkari** [nbschool/ecommerce_api#54]
Rapidamente vorrei che si unificassero un po' i test, cerchiamo di dagli un aspetto organico, e se c'e' codice duplicato da refactorare e da mettere in test utils.
Per esempio la creazione del database, della test up, il teardown, etc...

**Comment by GendoIkari** [comment]
Scriviamo due righe di README dove spieghiamo come fare per creare una classe di test, ereditando la nostra classe base.

**Comment by ceskomira90** [comment]
fatta con una nuova pull request
