### ISSUE TITLE
Fix: ordini vuoti e check di validità degli item

### ISSUE THREAD

**Issue by marcotinacci** [nbschool/ecommerce_api#56]
OrdersHandler::post denies an empty order answering BAD_REQUEST while OrderHandler::put accepts an empty order.

**Comment by GendoIkari** [comment]
E' anche peggio di cosi', abbiamo probabilmente un bug alla riga 58-60 di orders.py e i test non schiantano. Quindi da controllare che ci sia un bug, da fixare i test affinche' schiantino, e poi fixare il bug. E poi uniformare.

**Comment by dinghino** [comment]
un bug pare essere alla linea 60. la `get` ritorna una row sola, quindi da test vari mi risulta che ritorni il primo item che trova nella `items` list nella richiesta della post, se trova un match col nome (bruttissimo cercare per nome, imho), tant'è che se provo ad iterare mi dice che non è iterabile.

Posso provare a fargli fare una `select().where(Item.name << item_names)` per avere la lista effettiva di Items, **ma** questo non esclude che tu gli stia chiedendo di aggiungere un Item che non esiste... semplicemente non lo prende con la select e non lo aggiunge all'ordine, no? se è il comportamento voluto va bene, ma mi aspetterei un errore di sorta tipo `ItemNotFound` ad esempio.

**Comment by dinghino** [comment]
Riguardo l'issue aperto comunque ho aperto la PR: https://github.com/nbschool/ecommerce_api/pull/67 c'era solo un controllo sull'esistenza della key, non sul suo valore (credo colpa mia). cambiato il check, aggiunto un test per la post e per la patch con una lista di items vuota.
