### ISSUE TITLE
Jsonapi: patch con merge item

### ISSUE THREAD

**Issue by GendoIkari** [nbschool/ecommerce_api#58]
Una volta che abbiamo le patch (come #57) possiamo fare implementare un merge piu' appropriato nel caso degli item, degli order, etc... come vorrebbe la patch, invece che una semplice sostituzione.

http://jsonapi.org/faq/#wheres-put

Partendo dall'Item proviamo ad implementare un meccanismo di patch, dove mandiamo anche singoli campi nel json e "patchamo" l'item.

**Comment by gvaldambrini** [comment]
Come detto a voce, è necessario migliorare i test nel caso dell'item: è necessario fare almeno due test per ogni PATCH con successo: in un test si verificherà che venga modificato solo un campo, nell'altro si verificherà che la patch è usabile al posto della PUT e che modifichi correttamente tutti i campi. Sarà quindi anche necessario verificare non soltanto quanto salvato su database, ma anche quanto ritornato dalla vista.
