### ISSUE TITLE
Autenticazione REST

### ISSUE THREAD

**Issue by GendoIkari** [nbschool/ecommerce_api#6]
https://flask-httpauth.readthedocs.io/en/latest/
https://passlib.readthedocs.io/en/stable/

Possiamo autenticare le chiamate rest con HTTPBasic Auth, andando a mettere negli header delle richieste le informazioni username@password utilizzando flask-httpauth.

**Comment by GendoIkari** [comment]
Ho provato a lanciare i test e mi scoppiano tutti... note to self: lanciare i test prima di mergiare le pull request...

**Comment by GendoIkari** [comment]
Ok e' un problema di python 3.5 che non vuola nella json.loads bytes...

**Comment by GendoIkari** [comment]
Adesso sono gli item nelle risorse, c'e' da controllare l'autenticazione anche sui nuovi endpoint (forse non tutti).

**Comment by dinghino** [comment]
in teoria dovrebbe servire sugli items sarebbe da fare una volta che implementiamo un sistema di admin, no? sugli ordini mi torna (delete e edit solo dei tuoi ordini), ma per gli item...?
