### ISSUE TITLE
items patch may be bugged

### ISSUE THREAD

**Issue by dinghino** [nbschool/ecommerce_api#70]
sto implementando piano piano le jsonapi sui modelli e sulle views, test inclusi. arrivato agli Items stavo guardando la patch e ho l'impressione che possa avere problemi di implementazione.

da [specifiche](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH) (e [RFC5789 - PATCH Method](https://tools.ietf.org/html/rfc5789)) la patch è utilizzata per poter aggiornare risorse inviando solo i dati parziali da modificare, a differenza della put che prevede l'invio dell'intera risorsa modificata. 

Nel nostro caso degli Item mi aspetterei, tramite una richiesta patch verso un Item, di poter inviare solo il prezzo o la descrizione, ad esempio, giusto?

L'implentazione attuale mi sembra quella di una PUT, dove sono richiesti tutti i campi (nome, descrizione e prezzo) e vengono sovrascritti tutti quanti ad ogni richiesta.

Per come ho inteso la patch dovrebbe essere che:

* nessun campo è `required`
* almeno un campo deve essere presente (altrimenti cosa c'è da patchare? bad request)
* i campi devono essere sovrascritti solo se presenti nella richiesta

**Comment by gvaldambrini** [comment]
è noto, e parte di un percorso di migrazione graduale all'uso del patch
