### ISSUE TITLE
OrderItem::remove_item troppo permissiva

### ISSUE THREAD

**Issue by gvaldambrini** [nbschool/ecommerce_api#85]
Se la quantità di item da rimuovere è superiore alla disponibilità è un errore che deve essere segnalato (sarà necessario sollevare un'eccezione che terminerà in un BAD_REQUEST o in un INTERNAL_SERVER_ERROR a seconda che sia la API a prevedere di specificare la quantità da sottrarre o meno)

**Comment by dinghino** [comment]
l'idea era di averla permissiva ed utilizzarla come scorciatoia per la `delete_instance` di peewee, in modo da poter rimuovere completamente l'item da un ordine chiedendo di rimuoverne più di quanti ce ne sono, continuando però ad aggiornare correttamente l'Order (se vedi alla fine ritorna la quantità di item effettivamente "rimossi" dall'ordine).
Se la vuoi un po' più restrittiva comunque, visto che sto aggiustando la PR https://github.com/nbschool/ecommerce_api/pull/66, ci aggiungo pure questa cosa qua

**Comment by gvaldambrini** [comment]
Perché dovrebbe esserci il bisogno di rimuovere più elementi di quanti ce ne sono? Va bene eliminare l'Item quando la quantità diventa 0, ma non capisco il senso di averla negativa. E' il posto migliore per sotterrare un bug. Per quanto riguarda includerla nell'altra pr, teniamo le pr focalizzate solo sull'aspetto che le riguardano (e quindi siccome parla di add_items e transazioni, questo fix non c'entra niente).

**Comment by dinghino** [comment]
ok :)
