### ISSUE TITLE
Testare ed eventualment rimuovere il check globale sull'header per il json (get_json fa esattamente questo)

### ISSUE THREAD

**Issue by GendoIkari** [nbschool/ecommerce_api#87]
La get_json controlla gia' l'header del json, e poi abbiamo/avremo la validazione con gli schema di marshmallow. Il globalone che controlla l'header a TUTTE le richieste deve essere superfluo e quindi eliminato.

**Comment by gvaldambrini** [comment]
Attenzione, questo è solo in parte vero. La [get_json](http://flask.pocoo.org/docs/0.12/api/#flask.Request.get_json) ritorna `None` quando il mimetype non è quello corretto, mentre il globalone ritorna al client `BAD_REQUEST`. Sarà quindi necessario spostare quella logica nelle viste interessate.

**Comment by gvaldambrini** [comment]
Dato che con la jsonapi ci siamo quasi, per il momento non spostiamo la logica dal globalone alle singole viste. Sarà da rimuovere il globalone non appena fatto il merge di jsonapi.
