### ISSUE TITLE
Indagare come integrare le pictures nella jsonapi

### ISSUE THREAD

**Issue by gvaldambrini** [nbschool/ecommerce_api#98]
E' necessario integrare l'invio / ricezione di dati binari nella jsonapi. Bisogna capire come fare.

**Comment by marcotinacci** [comment]
http://discuss.jsonapi.org/t/download-attachments-using-json-api/644/4
Sembra che tramite json-api il modo standard sia spedire un campo con l'indirizzo dell'immagine, inoltre affiancare una richiesta con contenuto mime type alle json-api è una _perfectly valid solution_ .

Il tizio propone anche un encoding b64 infilato a forza in un file json a cui avevo pensato anche io, ma le performance ne risentirebbero e anche la risposta che gli viene data sembra sconsigliarlo.

**Comment by GendoIkari** [comment]
C'e' da aggiornare lo schema per le relationship almeno.
